/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Stats = {
  _id: string;
  _type: "stats";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventsWorldwide?: number;
  peopleImpacted?: number;
  yearsExperience?: number;
};

export type ContactInfo = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone?: string;
  email?: string;
  socialLinks?: {
    x?: string;
    instagram?: string;
    linkedin?: string;
    spotify?: string;
    soundcloud?: string;
    applePodcast?: string;
    youtubeMusic?: string;
  };
};

export type GalleryImage = {
  _id: string;
  _type: "galleryImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  altText?: string;
  rotation?: "rotate-left" | "rotate-right" | "straight";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  author?: string;
  locationOrRole?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "room" | "listener";
};

export type Episode = {
  _id: string;
  _type: "episode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  listenUrl?: string;
  publishDate?: string;
  episodeNumber?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Stats | ContactInfo | GalleryImage | Testimonial | Episode | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./lib/sanity/queries.ts
// Variable: getEpisodesQuery
// Query: *[_type == "episode"] | order(publishDate desc, _createdAt desc) {    _id,    title,    description,    listenUrl,    publishDate  }
export type GetEpisodesQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  listenUrl: string | null;
  publishDate: string | null;
}>;
// Variable: getAllTestimonialsQuery
// Query: *[_type == "testimonial"] | order(_createdAt desc) {    _id,    quote,    author,    locationOrRole,    category,    "avatarUrl": avatar.asset->url,    "avatarLqip": avatar.asset->metadata.lqip  }
export type GetAllTestimonialsQueryResult = Array<{
  _id: string;
  quote: string | null;
  author: string | null;
  locationOrRole: string | null;
  category: "listener" | "room" | null;
  avatarUrl: string | null;
  avatarLqip: string | null;
}>;
// Variable: getGalleryImagesQuery
// Query: *[_type == "galleryImage"] | order(orderRank) [0...$limit] {    _id,    altText,    "imageUrl": image.asset->url,    "imageLqip": image.asset->metadata.lqip  }
export type GetGalleryImagesQueryResult = Array<{
  _id: string;
  altText: string | null;
  imageUrl: string | null;
  imageLqip: string | null;
}>;
// Variable: getMoreGalleryImagesQuery
// Query: *[_type == "galleryImage" && orderRank > $lastOrderRank] | order(orderRank) [0...$limit] {    _id,    altText,    "imageUrl": image.asset->url,    "imageLqip": image.asset->metadata.lqip,    orderRank  }
export type GetMoreGalleryImagesQueryResult = Array<{
  _id: string;
  altText: string | null;
  imageUrl: string | null;
  imageLqip: string | null;
  orderRank: null;
}>;
// Variable: getInitialGalleryImagesQuery
// Query: *[_type == "galleryImage"] | order(orderRank) [0...$limit] {    _id,    altText,    "imageUrl": image.asset->url,    "imageLqip": image.asset->metadata.lqip,    orderRank  }
export type GetInitialGalleryImagesQueryResult = Array<{
  _id: string;
  altText: string | null;
  imageUrl: string | null;
  imageLqip: string | null;
  orderRank: null;
}>;
// Variable: getContactInfoQuery
// Query: *[_type == "contactInfo"][0] {    phone,    email,    socialLinks {      x,      instagram,      linkedin,      spotify,      soundcloud,      applePodcast,      youtubeMusic    }  }
export type GetContactInfoQueryResult = {
  phone: string | null;
  email: string | null;
  socialLinks: {
    x: string | null;
    instagram: string | null;
    linkedin: string | null;
    spotify: string | null;
    soundcloud: string | null;
    applePodcast: string | null;
    youtubeMusic: string | null;
  } | null;
} | null;
// Variable: getStatsQuery
// Query: *[_type == "stats"][0] {    eventsWorldwide,    peopleImpacted,    yearsExperience  }
export type GetStatsQueryResult = {
  eventsWorldwide: number | null;
  peopleImpacted: number | null;
  yearsExperience: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"episode\"] | order(publishDate desc, _createdAt desc) {\n    _id,\n    title,\n    description,\n    listenUrl,\n    publishDate\n  }\n": GetEpisodesQueryResult;
    "\n  *[_type == \"testimonial\"] | order(_createdAt desc) {\n    _id,\n    quote,\n    author,\n    locationOrRole,\n    category,\n    \"avatarUrl\": avatar.asset->url,\n    \"avatarLqip\": avatar.asset->metadata.lqip\n  }\n": GetAllTestimonialsQueryResult;
    "\n  *[_type == \"galleryImage\"] | order(orderRank) [0...$limit] {\n    _id,\n    altText,\n    \"imageUrl\": image.asset->url,\n    \"imageLqip\": image.asset->metadata.lqip\n  }\n": GetGalleryImagesQueryResult;
    "\n  *[_type == \"galleryImage\" && orderRank > $lastOrderRank] | order(orderRank) [0...$limit] {\n    _id,\n    altText,\n    \"imageUrl\": image.asset->url,\n    \"imageLqip\": image.asset->metadata.lqip,\n    orderRank\n  }\n": GetMoreGalleryImagesQueryResult;
    "\n  *[_type == \"galleryImage\"] | order(orderRank) [0...$limit] {\n    _id,\n    altText,\n    \"imageUrl\": image.asset->url,\n    \"imageLqip\": image.asset->metadata.lqip,\n    orderRank\n  }\n": GetInitialGalleryImagesQueryResult;
    "\n  *[_type == \"contactInfo\"][0] {\n    phone,\n    email,\n    socialLinks {\n      x,\n      instagram,\n      linkedin,\n      spotify,\n      soundcloud,\n      applePodcast,\n      youtubeMusic\n    }\n  }\n": GetContactInfoQueryResult;
    "\n  *[_type == \"stats\"][0] {\n    eventsWorldwide,\n    peopleImpacted,\n    yearsExperience\n  }\n": GetStatsQueryResult;
  }
}
